/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateCompletionRequestStop : Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct CreateCompletionRequestStop {}

impl CreateCompletionRequestStop {
    /// Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
    pub fn new() -> CreateCompletionRequestStop {
        CreateCompletionRequestStop {}
    }
}
