/*
 * OpenAI API
 *
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct ListFineTunesResponse {
    #[serde(rename = "object")]
    pub object: String,
    #[serde(rename = "data")]
    pub data: Vec<crate::models::FineTune>,
}

impl ListFineTunesResponse {
    pub fn new(object: String, data: Vec<crate::models::FineTune>) -> ListFineTunesResponse {
        ListFineTunesResponse { object, data }
    }
}
